---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sidd9433/spring-cloudconfig-ko-tolls
          # username:
          # password:
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/sidd9433/spring-cloudconfig-ko-tolls-perf
              search-paths:
                - 'station*'